name: Dependent Jobs Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Start Build
        run: echo "Building application..."
      - name: Simulate Build
        run: sleep 5

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Start Testing
        run: echo "Running tests..."
      - name: Simulate Tests
        run: sleep 5

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Start Deployment
        run: echo "Building application - Part B"

      - name: Simulate Deployment
        run: sleep 5
